<?php
// Generated by Zend Framework 2
return array(
    'Application\Module'                     => __DIR__ . '/module/Application/Module.php',
    'Application\Controller\IndexController' => __DIR__ . '/module/Application/src/Application/Controller/IndexController.php',
    'Formulario\Module'                      => __DIR__ . '/module/Formulario/Module.php',
);