<?php
// module/Album/view/album/album/add.phtml:

$title = 'FORMULARIO CONOCIMIENTO SOCIO E INSPECCION';
$this->headTitle($title);
?>
<h1 class="titulo-formulario"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('formulario', array('action' => 'guardar')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('per_id'));
?>
<div class="datos-personales grupo">
<h3>Datos Personales</h3>
<hr>
<div class='form-group'><?php echo $this->formRow($form->get('pai_id')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_documento')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_nombres')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_apellido_paterno')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_apellido_materno')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_nacimiento_lugar')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_nacimiento_fecha')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_sexo')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_dependientes')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_estado_civil')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_conyuge_nombre')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_conyuge_documento')); ?></div>

</div>
<div class="direccion-domiciliaria grupo">
<h3>Dirección Domiciliaria</h3>
<hr>
<div class='form-group'><?php echo $this->formRow($form->get('pro_id')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ciu_id')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('par_id')); ?></div>   
<div class='form-group'><?php echo $this->formRow($form->get('per_barrio')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_direccion')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_tiempo_residencia')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_telefono')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_celular')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_email')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_tipo_vivienda')); ?></div>

</div>

<div class="descripcion-actividad grupo">
<h3>Descripción de la Actividad Económica</h3>
<hr>
<div class='form-group'><?php echo $this->formRow($form->get('act_eco_id')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_numero_empleados')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_tipo')); ?></div>

</div>

<div class="actividad-economica grupo">
<h3>Actividad Económica</h3>
<hr>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_producto')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_inicio')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_nombre')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_cargo')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_ruc')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_direccion')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_referencia')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_telefono')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_celular')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('per_empresa_email')); ?></div>

</div>

<div class="informacion-financiera grupo">
<h3>Información Financiera</h3>
<hr>
<div class="subgrupo">
<h4>INGRESOS</h4>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_arriendos1')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_remesas2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_sueldo_solicitante3'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_sueldo_conyuge4'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_pensiones5'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_ingresos_negocio6'));?></div>
</div>
<div class="subgrupo">
<h4>EGRESOS</h4>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_alimentacion7')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_educacion8'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_servicios_basicos9'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_arriendo_gasto10'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_otros11'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_deudas12'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_combustible13'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_transporte14'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_vestuario15'));?></div>
</div>
</div>

<div class="situacion-financiera grupo">
<h3>Situación Financiera</h3>
<hr>
<div class="subgrupo">
<h4>Descripción Activos</h4>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_bancos1')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_inversiones2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_cuentas3'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_mercaderia4'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_muebles5'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_vehiculos6'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_propiedades7'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_activos8'));?></div>
</div>
<div class="subgrupo">
<h4>Descripción Pasivos</h4>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_prestamos9')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_cuentas_pagar10'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_otras_obligaciones11'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_prestamo12'));?></div>
</div>
<hr>
</div>

<div class="referencias grupo">
<h3>Referencias Personales,Comerciales y Bancarias</h3>   
<hr>
<div class="subgrupo">
<h4>Personales(Familiares o amistades que no vivan con Ud.)</h4>
<div class='form-group'><?php echo $this->formRow($form->get('ref_per_nombres[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_per_direccion[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_per_telefono[]'));?></div>

<div class='form-group'><?php echo $this->formRow($form->get('ref_per_nombres[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_per_direccion[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_per_telefono[]'));?></div>
</div>
<div class="subgrupo">
<h4>Comerciales</h4>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_nombres[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_direccion[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_telefono[]'));?></div>

<div class='form-group'><?php echo $this->formRow($form->get('ref_com_nombres[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_direccion[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_telefono[]'));?></div>
</div>
<div class="subgrupo">
<h4>Bancarias</h4>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_banco[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_tipo_cuenta[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_numero_cuenta[]'));?></div>

<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_banco[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_tipo_cuenta[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_numero_cuenta[]'));?></div>
</div>
<div class="subgrupo">
<h4>Tarjetas de Crédito</h4>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_institucion[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_numero_tarjeta[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_anio_socio[]'));?></div>

<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_institucion[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_numero_tarjeta[]'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_anio_socio[]'));?></div>
</div>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<script type="text/javascript">
    $(function() {
        $( "#per_nacimiento_fecha,#per_empresa_inicio" ).datepicker({
		dateFormat:'yy/mm/dd',
		changeMonth: true,
		 changeYear: true,
		 yearRange: '-150:+0',
		 showOn: "button",
                buttonImage: "<?php echo $this->basePath('img/calendar.gif')?>",
                buttonImageOnly: true
	});
             
        $("#ciu_id").prop("disabled", true);
        $("#par_id").prop("disabled", true);

        $("#pro_id").change(function() {
            $.ajax({
                url: "<?php echo $this->url('formulario', array('controller' => 'formulario', 'action' => 'ciudades')) ?>",
                type: "POST",
                dataType: "json",
                data: "provincia=" + $(this).val(),
                beforeSend: function() {
                    $("#ciu_id").prop("disabled", true);
                }
            }).done(function(ciudades) {
                $("#ciu_id").html("");
                $("#ciu_id").append('<option>Escoja la ciudad</option>');
                for (ciudad in ciudades) {
                    $("#ciu_id").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
                }
                $("#ciu_id").prop("disabled", false);
            });
        });

        $("#ciu_id").change(function() {
            $.ajax({
                url: "<?php echo $this->url('formulario', array('controller' => 'formulario', 'action' => 'parroquias')) ?>",
                type: "POST",
                dataType: "json",
                data: "ciudad=" + $(this).val(),
                beforeSend: function() {
                    $("#par_id").prop("disabled", true);
                }
            }).done(function(parroquias) {
                $("#par_id").html("");
                $("#par_id").append('<option>Escoja la parroquia</option>');
                for (parroquia in parroquias) {
                    $("#par_id").append('<option value="' + parroquia + '">' + parroquias[parroquia] + '</option>');
                }
                $("#par_id").prop("disabled", false);
            });
        });

    });
</script>


