<?php

$title = 'Formulario Socio/Cliente';
$this->headTitle($title);
?>
<h1 class="titulo-formulario"><?php echo $this->escapeHtml($title); ?></h1>
<?php if(isset($this->message)):?>
<div class="alert alert-danger"><?php echo $this->message?></div>
<?php endif; ?>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('formulario', array('action' => 'guardar')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('per_id'));
?>
<h3>Datos Personales</h3>
<div class="datos-personales grupo">
    <div class="section">
        <div class='form-group'><?php echo $this->formRow($form->get('tipo_documento')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_documento')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_apellido_paterno')); ?></div>
    </div>
    <div class="section">
        <div class='form-group'><?php echo $this->formRow($form->get('per_apellido_materno')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_nombres')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_nacimiento_lugar')); ?></div>
    </div>
    <div class="section">
        <div class='form-group d-picker'><?php echo $this->formRow($form->get('per_nacimiento_fecha')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_sexo')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_dependientes')); ?></div>
    </div>
    <div class="section" style="border:none;">
        <div class='form-group'><?php echo $this->formRow($form->get('per_estado_civil')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_conyuge_nombre')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_conyuge_documento')); ?></div>
    </div>
</div>
<h3>Dirección Domiciliaria</h3>
<div class="direccion-domiciliaria grupo">
    <div class="section">
        <div class='form-group'><?php echo $this->formRow($form->get('pai_id')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('pro_id')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('ciu_id')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('par_id')); ?></div> 
    </div>
    <div class="section">
        <div class='form-group'><?php echo $this->formRow($form->get('per_barrio')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_direccion')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_tiempo_residencia')); ?></div>
    </div>
    <div class="section">
        <div class='form-group'><?php echo $this->formRow($form->get('per_telefono')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_celular')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_email')); ?></div>
    </div>
    <div class="section" style="border:none;">
        <div class='form-group'><?php echo $this->formRow($form->get('per_tipo_vivienda')); ?></div>
    </div>
</div>
<h3>Descripción de la Actividad Económica</h3>
<div class="descripcion-actividad grupo">
    <div class="section">
        <div class='form-group'><?php echo $this->formRow($form->get('act_eco_id')); ?></div>
        <div class='form-group'><?php echo $this->formRow($form->get('per_numero_empleados')); ?></div>
    </div>
    <div class="section" style="border:none;">
        <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_tipo')); ?></div>
    </div>

</div>
<h3>Actividad Económica</h3>
<div class="actividad-economica grupo">
        <div class="section">
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_producto')); ?></div>
        </div>
        <div class="section">
            <div class='form-group d-picker'><?php echo $this->formRow($form->get('per_empresa_inicio')); ?></div>
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_nombre')); ?></div>
        </div>
        <div class="section">
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_cargo')); ?></div>
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_ruc')); ?></div>
        </div>
        <div class="section">
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_direccion')); ?></div>
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_referencia')); ?></div>
        </div>
        <div class="section">
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_telefono')); ?></div>
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_celular')); ?></div>
        </div>
        <div class="section" style="border:none;">
            <div class='form-group'><?php echo $this->formRow($form->get('per_empresa_email')); ?></div>
        </div>
</div>

<h3>Información Financiera</h3>
<div class="informacion-financiera grupo">
<div class="subgrupo ingresos">
<h4>INGRESOS</h4>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_arriendos1')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_remesas2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_sueldo_solicitante3'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_sueldo_conyuge4'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_pensiones5'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_ingresos_negocio6'));?></div>
</div>
<div class="subgrupo egresos">
<h4>EGRESOS</h4>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_alimentacion7')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_educacion8'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_servicios_basicos9'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_arriendo_gasto10'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_otros11'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_deudas12'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_combustible13'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_transporte14'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('inf_fin_vestuario15'));?></div>
</div>
</div>

<h3>Situación Financiera</h3>
<div class="situacion-financiera grupo">
<div class="subgrupo activos">
<h4>Descripción Activos</h4>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_bancos1')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_inversiones2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_cuentas3'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_mercaderia4'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_muebles5'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_vehiculos6'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_propiedades7'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_activos8'));?></div>
</div>
<div class="subgrupo pasivos">
<h4>Descripción Pasivos</h4>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_prestamos9')); ?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_cuentas_pagar10'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_otras_obligaciones11'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('sit_fin_prestamo12'));?></div>
</div>
</div>

<h3>Referencias Personales,Comerciales y Bancarias</h3>   
<div class="referencias grupo">  
<div class="subgrupo personales">
<h4>Personales(Familiares o amistades que no vivan con Ud.)</h4>
<div class="section">
    <div class='form-group'><?php echo $this->formRow($form->get('ref_per_nombres1'));?></div>
    <div class='form-group'><?php echo $this->formRow($form->get('ref_per_direccion1'));?></div>
    <div class='form-group'><?php echo $this->formRow($form->get('ref_per_telefono1'));?></div>
</div>
<div class="section" style="border:none;">
    <div class='form-group'><?php echo $this->formRow($form->get('ref_per_nombres2'));?></div>
    <div class='form-group'><?php echo $this->formRow($form->get('ref_per_direccion2'));?></div>
    <div class='form-group'><?php echo $this->formRow($form->get('ref_per_telefono2'));?></div>
</div>
</div>
<div class="subgrupo comerciales">
<h4>Comerciales</h4>
<div class="section">
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_nombres1'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_direccion1'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_telefono1'));?></div>
</div>

<div class='form-group'><?php echo $this->formRow($form->get('ref_com_nombres2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_direccion2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_com_telefono2'));?></div>

</div>
<div class="subgrupo bancarias">
<h4>Bancarias</h4>
<div class="section">
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_banco1'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_tipo_cuenta1'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_numero_cuenta1'));?></div>
</div>

<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_banco2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_tipo_cuenta2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('ref_ban_numero_cuenta2'));?></div>

</div>
<div class="subgrupo credito">
<h4>Tarjetas de Crédito</h4>
<div class="section">
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_institucion1'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_numero_tarjeta1'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_anio_socio1'));?></div>
</div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_institucion2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_numero_tarjeta2'));?></div>
<div class='form-group'><?php echo $this->formRow($form->get('tar_cre_anio_socio2'));?></div>
</div>
<div class="subgrupo" style="border:none;">
<h4>Servicios</h4>
<div class='form-group'><?php echo $this->formRow($form->get('per_tarjeta_credito'));?></div>
</div>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<script type="text/javascript">
    $(function() {
        $( "#per_nacimiento_fecha,#per_empresa_inicio" ).datepicker({
		dateFormat:'yy/mm/dd',
		changeMonth: true,
		 changeYear: true,
		 yearRange: '-150:+0',
		 showOn: "button",
                buttonImage: "<?php echo $this->basePath('img/calendar.gif')?>",
                buttonImageOnly: true
	});
        
        <?php if($this->flag=='crear'):?>
        $("#ciu_id").prop("disabled", true);
        $("#par_id").prop("disabled", true);
        <?php endif;?>
            
        <?php if($this->flag=='editar'):?>
        var pro_id = $('#pro_id').val();
        if(pro_id == ''){
            $("#ciu_id").prop("disabled", true);
            $("#par_id").prop("disabled", true);
        }else{
            $("#ciu_id").prop("disabled", false);
            $("#par_id").prop("disabled", false);
        }
        <?php endif;?>

        $("#pro_id").change(function() {
            $.ajax({
                url: "<?php echo $this->url('formulario', array('controller' => 'formulario', 'action' => 'ciudades')) ?>",
                type: "POST",
                dataType: "json",
                data: "provincia=" + $(this).val(),
                beforeSend: function() {
                    $("#ciu_id").prop("disabled", true);
                }
            }).done(function(ciudades) {
                $("#ciu_id").html("");
                $("#ciu_id").append('<option>Escoja la ciudad</option>');
                for (ciudad in ciudades) {
                    $("#ciu_id").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
                }
                $("#ciu_id").prop("disabled", false);
            });
        });

        $("#ciu_id").change(function() {
            $.ajax({
                url: "<?php echo $this->url('formulario', array('controller' => 'formulario', 'action' => 'parroquias')) ?>",
                type: "POST",
                dataType: "json",
                data: "ciudad=" + $(this).val(),
                beforeSend: function() {
                    $("#par_id").prop("disabled", true);
                }
            }).done(function(parroquias) {
                $("#par_id").html("");
                $("#par_id").append('<option>Escoja la parroquia</option>');
                for (parroquia in parroquias) {
                    $("#par_id").append('<option value="' + parroquia + '">' + parroquias[parroquia] + '</option>');
                }
                $("#par_id").prop("disabled", false);
            });
        });

    });
</script>


